workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - google_play # Add your credentials in Codemagic UI
    scripts:
      - name: Set up local properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/flutter/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd flutter
          flutter pub get
      - name: Build APK
        script: |
          cd flutter
          flutter build apk --release
      - name: Build App Bundle
        script: |
          cd flutter
          flutter build appbundle --release
    artifacts:
      - flutter/build/**/outputs/**/*.apk
      - flutter/build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - tooyakov.art@gmail.com

  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: X5 Marketing # Add your App Store Connect API key in Codemagic UI
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.x5marketing.app
      vars:
        APP_STORE_APPLE_ID: "YOUR_APPLE_ID" # Replace with your Apple ID
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd flutter
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd flutter/ios
          pod install
      - name: Build iOS
        script: |
          cd flutter
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - flutter/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - tooyakov.art@gmail.com

  web-deploy:
    name: Web Deploy to Firebase
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      node: 18
      groups:
        - firebase # Add FIREBASE_TOKEN in Codemagic UI
    scripts:
      - name: Install dependencies
        script: |
          cd web
          npm install
      - name: Build web
        script: |
          cd web
          npm run build
      - name: Deploy to Firebase
        script: |
          cd web
          npm install -g firebase-tools
          firebase deploy --only hosting --project x5-marketing-app --token "$FIREBASE_TOKEN"
    publishing:
      email:
        recipients:
          - tooyakov.art@gmail.com
